/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weitang114_opencvcircledetecttest_NativeCircleDetector */

#ifndef _Included_design_software_little_practice_circledetection_NativeCircleDetector
#define _Included_design_software_little_practice_circledetection_NativeCircleDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weitang114_opencvcircledetecttest_NativeCircleDetector
 * Method:    nativeDetect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_design_software_little_1practice_circledetection_NativeCircleDetector_nativeDetect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
